"""EPC gallery registry: per-pattern display metadata + visualization choice.
Names/references mirror docs/catalog_complete_summary.md; canonical metric mirrors
epc/phase2a/continuous_metrics.py."""

# pid -> dict(name, ref, viz, args, summary, effect)
GALLERY = {
"P1":  dict(name="Similarity-driven aggregation", ref="Schelling 1971", viz="grid_field",
   summary="Agents relocate when too few neighbours share their type.",
   effect="Mild individual preference produces large segregated clusters."),
"P2":  dict(name="Activity-induced phase separation (MIPS)", ref="Fily & Marchetti 2012", viz="point_cloud",
   summary="Self-propelled particles slow where crowded (density-dependent motility).",
   effect="Dense and dilute phases coexist with no attractive force."),
"P3":  dict(name="Turing pattern formation", ref="Gray-Scott (Pearson 1993)", viz="grid_field",
   summary="Reaction-diffusion with a fast inhibitor and slow activator.",
   effect="A stationary labyrinth at a selected wavelength self-organises from near-uniformity."),
"P4":  dict(name="Territoriality / exclusion", ref="Giuggioli et al. 2011", viz="point_cloud",
   summary="Agents deposit and avoid foreign scent as they move.",
   effect="Exclusive home ranges with sharp boundaries emerge."),
"P5":  dict(name="Flocking / alignment", ref="Vicsek et al. 1995", viz="point_cloud",
   summary="Each agent steers toward the mean heading of neighbours.",
   effect="Global polar order (a moving flock) emerges below a noise threshold."),
"P6":  dict(name="Milling / vortex", ref="D'Orsogna et al. 2006", viz="point_cloud",
   summary="Self-propulsion plus attraction-repulsion forces.",
   effect="A rotating mill (nonzero angular momentum) forms."),
"P7":  dict(name="Lane formation", ref="Helbing & Molnar 1995", viz="point_cloud",
   summary="Two opposing streams of agents avoid collisions.",
   effect="Counter-flowing lanes self-organise."),
"P8":  dict(name="Self-organized traffic jams", ref="Nagel-Schreckenberg 1992", viz="timeseries",
   summary="Cars accelerate, brake, and randomly dawdle on a 1-D road.",
   effect="Stop-and-go jams appear spontaneously above a density."),
"P9":  dict(name="Synchronization", ref="Kuramoto 1975", viz="phase_circle",
   summary="Coupled phase oscillators with a spread of natural frequencies.",
   effect="Above a critical coupling the population phase-locks."),
"P10": dict(name="Chimera states", ref="Abrams & Strogatz 2004", viz="phase_circle",
   summary="Non-locally coupled identical oscillators.",
   effect="Coherent and incoherent groups coexist simultaneously."),
"P11": dict(name="Predator-prey oscillation", ref="Mobilia et al. 2007", viz="grid_field",
   summary="Spatial Lotka-Volterra predation on a lattice.",
   effect="Anti-correlated population cycles with travelling fronts."),
"P12": dict(name="Cyclic dominance (RPS)", ref="Reichenbach et al. 2007", viz="grid_field",
   summary="Three species in rock-paper-scissors competition on a lattice.",
   effect="Self-sustaining spiral waves maintain coexistence."),
"P13": dict(name="Excitable spiral / target waves", ref="Greenberg-Hastings 1978", viz="grid_field",
   summary="Excitable cells with refractory recovery.",
   effect="Self-sustaining spiral and target waves propagate."),
"P14": dict(name="Self-organized criticality", ref="Bak-Tang-Wiesenfeld 1987", viz="distribution",
   args=dict(key="avalanche_sizes", mode="loglog"),
   summary="A driven sandpile topples when slope exceeds threshold.",
   effect="Avalanches follow a scale-free power law without tuning."),
"P15": dict(name="Persistent propagating computation", ref="Conway Game of Life", viz="grid_field",
   summary="Deterministic life-like cellular automaton.",
   effect="Propagating structures carry and transform information."),
"P16": dict(name="Associative memory", ref="Hopfield 1982", viz="timeseries",
   summary="A symmetric recurrent net relaxes from a corrupted cue.",
   effect="The network completes the cue to the nearest stored pattern."),
"P17": dict(name="Collective gradient sensing", ref="Berdahl et al. 2013", viz="point_cloud",
   summary="Agents with noisy individual sensing follow social cues.",
   effect="The group climbs a gradient no individual can resolve."),
"P18": dict(name="Consensus / coarsening", ref="Voter model (Holley-Liggett 1975)", viz="grid_field",
   summary="Each agent copies a random neighbour's opinion.",
   effect="Opinion domains coarsen toward consensus."),
"P19": dict(name="Emergent leadership", ref="Couzin et al. 2005", viz="point_cloud",
   summary="A small informed minority has a preferred direction.",
   effect="The uninformed majority is steered accurately by a few."),
"P20": dict(name="Quorum sensing", ref="Waters & Bassler 2005", viz="timeseries",
   args=dict(key="fraction_on"),
   summary="Agents switch ON when local signal crosses a threshold.",
   effect="A sharp, hysteretic collective switch at a critical density."),
"P21": dict(name="Polarization / fragmentation", ref="Hegselmann-Krause 2002", viz="distribution",
   args=dict(key="opinions", mode="hist"),
   summary="Bounded-confidence opinion dynamics.",
   effect="A unimodal population fragments into separated camps."),
"P22": dict(name="Information cascade / contagion", ref="SIR (Datta-Acharyya 2021)", viz="grid_field",
   summary="Susceptible-infected-recovered spread on a lattice.",
   effect="An epidemic wavefront sweeps the population."),
"P23": dict(name="Anti-coordination / load balancing", ref="Minority Game (Savit 1999)", viz="timeseries",
   summary="Agents win by choosing the minority side.",
   effect="Attendance self-balances with sub-random (efficient) variance."),
"P24": dict(name="Homeostatic regulation", ref="Ashby 1956", viz="timeseries",
   summary="Feedback drives a variable back to its set-point.",
   effect="The regulated variable rejects perturbations and holds set-point."),
"P25": dict(name="Canalized restoration / equifinality", ref="Waddington 1957", viz="timeseries",
   summary="Many initial conditions flow down a canalized landscape.",
   effect="Different starts converge to the same attractor macrostate."),
"P26": dict(name="Stochastic resonance", ref="Gammaitoni 1998", viz="timeseries",
   summary="A sub-threshold signal plus tuned noise in a bistable unit.",
   effect="Optimal noise maximises signal detection (inverted-U)."),
"P27": dict(name="Spatial reciprocity", ref="Nowak & May 1992", viz="grid_field",
   summary="Cooperators and defectors play neighbours on a lattice.",
   effect="Cooperation survives by forming spatial clusters."),
"P28": dict(name="Wealth condensation", ref="Yard-Sale (Chakraborti 2002)", viz="distribution",
   args=dict(key="wealth", mode="lorenz"),
   summary="Agents repeatedly trade a random fraction of wealth.",
   effect="Wealth spontaneously condenses to extreme inequality."),
"P29": dict(name="Trail / network formation", ref="Tero et al. 2010 (Physarum)", viz="network",
   summary="Agents reinforce and evaporate trails between nodes.",
   effect="An efficient near-minimal transport network emerges."),
"P30": dict(name="Autopoiesis / boundary formation", ref="Varela-Maturana-Uribe 1974", viz="point_cloud",
   summary="Catalysis links substrate particles into a membrane that decays.",
   effect="A self-maintaining closed boundary forms and persists."),
"P31": dict(name="Delayed gratification", ref="Zhang et al. 2024", viz="spacetime",
   summary="Agents forgo immediate reward for larger later payoff.",
   effect="Per-agent restraint carries information beyond the policy label."),
"P32": dict(name="Emergent specialization", ref="Bonabeau 1996", viz="network",
   summary="Response-threshold agents take tasks they sense most.",
   effect="Division of labour emerges as roles differentiate."),
}
