"""EPC gallery registry: per-pattern display metadata + visualization choice.
Names/references mirror docs/catalog_complete_summary.md; canonical metric mirrors
epc/phase2a/continuous_metrics.py."""

# pid -> dict(name, ref, viz, args, summary, effect)
GALLERY = {
"P1":  dict(name="Similarity-driven aggregation", ref="Schelling 1971", viz="grid_field",
   args=dict(legend=["empty", "group A", "group B"], empty_idx=0),
   summary="Agents relocate when too few neighbours share their type.",
   watch="Watch the two intermixed groups sort into large single-colour blocks (empty cells stay grey) — nobody is forced, yet sharp segregated neighbourhoods form.",
   effect="Mild individual preference produces large segregated clusters."),
"P2":  dict(name="Activity-induced phase separation (MIPS)", ref="Fily & Marchetti 2012", viz="point_cloud",
   summary="Self-propelled particles slow where crowded (density-dependent motility).",
   watch="Watch evenly-spread particles clump into dense blobs while gaps stay empty — clustering with no attraction, just crowding.",
   effect="Dense and dilute phases coexist with no attractive force."),
"P3":  dict(name="Turing pattern formation", ref="Gray-Scott (Pearson 1993)", viz="grid_field",
   args=dict(sample="even"),
   summary="Reaction-diffusion with a fast inhibitor and slow activator.",
   watch="Watch the near-uniform field break into a maze of stripes/spots at one repeating spacing.",
   effect="A stationary labyrinth at a selected wavelength self-organises from near-uniformity."),
"P4":  dict(name="Territoriality / exclusion", ref="Giuggioli et al. 2011", viz="occupancy_field",
   summary="Agents deposit and avoid foreign scent as they move.",
   watch="Watch each cell take the colour of the agent that visits it most — distinct, non-overlapping coloured patches crystallise into exclusive home ranges.",
   effect="Exclusive home ranges with sharp boundaries emerge."),
"P5":  dict(name="Flocking / alignment", ref="Vicsek et al. 1995", viz="point_cloud",
   summary="Each agent steers toward the mean heading of neighbours.",
   watch="Watch the randomly-pointing arrows swing into one shared direction and move as a single flock.",
   effect="Global polar order (a moving flock) emerges below a noise threshold."),
"P6":  dict(name="Milling / vortex", ref="D'Orsogna et al. 2006", viz="point_cloud",
   summary="Self-propulsion plus attraction-repulsion forces.",
   watch="Watch the swarm curl into a rotating ring (a vortex) circling a hollow centre.",
   effect="A rotating mill (nonzero angular momentum) forms."),
"P7":  dict(name="Lane formation", ref="Helbing & Molnar 1995", viz="point_cloud",
   summary="Two opposing streams of agents avoid collisions.",
   watch="Watch the two opposing crowds sort into parallel lanes that slide past each other.",
   effect="Counter-flowing lanes self-organise."),
"P8":  dict(name="Self-organized traffic jams", ref="Nagel-Schreckenberg 1992", viz="traffic_spacetime",
   summary="Cars accelerate, brake, and randomly dawdle on a 1-D road.",
   watch="Watch red bands of stopped cars (jams) form on their own and drift BACKWARD against the flow — diagonal stripes leaning upstream as time goes up.",
   effect="Stop-and-go jams appear spontaneously and propagate backward."),
"P9":  dict(name="Synchronization", ref="Kuramoto 1975", viz="phase_circle",
   summary="Coupled phase oscillators with a spread of natural frequencies.",
   watch="Watch dots scattered around the circle bunch into one tight cluster — the oscillators fall into step (the red arrow grows).",
   effect="Above a critical coupling the population phase-locks."),
"P10": dict(name="Chimera states", ref="Abrams & Strogatz 2004", viz="phase_space",
   summary="Non-locally coupled identical oscillators.",
   watch="Watch one contiguous stretch of positions settle into a smooth phase band (locked) while the rest scatter across all phases — order and disorder side by side.",
   effect="Coherent and incoherent groups coexist simultaneously in space."),
"P11": dict(name="Predator-prey oscillation", ref="Mobilia et al. 2007", viz="pop_time",
   summary="Spatial Lotka-Volterra predation on a lattice.",
   watch="Watch the prey and predator populations rise and fall in repeating cycles — each predator peak trailing just behind a prey peak.",
   effect="Anti-correlated predator-prey population cycles."),
"P12": dict(name="Cyclic dominance (RPS)", ref="Reichenbach et al. 2007", viz="grid_field",
   args=dict(legend=["empty", "rock", "paper", "scissors"], empty_idx=0),
   summary="Three species in rock-paper-scissors competition on a lattice.",
   watch="Watch rotating spiral waves of the three colours endlessly chase one another, so none dies out.",
   effect="Self-sustaining spiral waves maintain coexistence."),
"P13": dict(name="Excitable spiral / target waves", ref="Greenberg-Hastings 1978", viz="grid_field",
   summary="Excitable cells with refractory recovery.",
   watch="Watch curved wavefronts sweep across the lattice and spiral around their cores — as each passes, cells fire then go dark (refractory), so the waves keep regenerating and never settle.",
   effect="Self-sustaining spiral and target waves propagate."),
"P14": dict(name="Self-organized criticality", ref="Bak-Tang-Wiesenfeld 1987", viz="dist_accumulate",
   args=dict(key="avalanche_sizes"),
   summary="A driven sandpile topples when slope exceeds threshold.",
   watch="On these log-log axes a straight line means avalanches come in every size with no typical scale.",
   effect="Avalanches follow a scale-free power law without tuning."),
"P15": dict(name="Persistent propagating computation", ref="Conway 1970 (Game of Life)", viz="grid_field",
   args=dict(legend=["dead", "alive"], empty_idx=0),
   summary="Deterministic life-like cellular automaton.",
   watch="Watch small structures glide and collide, carrying information across the grid.",
   effect="Propagating structures carry and transform information."),
"P16": dict(name="Associative memory", ref="Hopfield 1982", viz="vector_grid",
   args=dict(key="state"),
   summary="A symmetric recurrent net relaxes from a corrupted cue.",
   watch="Watch the overlap climb toward 1 as the network cleans a corrupted cue back into a stored memory.",
   effect="The network completes the cue to the nearest stored pattern."),
"P17": dict(name="Collective gradient sensing", ref="Berdahl et al. 2013", viz="gradient_climb",
   summary="Agents with noisy individual sensing follow social cues.",
   watch="Watch each agent's own gradient reading (dot colour) stay noisy, yet the group centroid (red trail) climbs steadily toward the source — many noisy individuals average into accurate collective navigation.",
   effect="The group climbs a gradient no individual can resolve."),
"P18": dict(name="Consensus / coarsening", ref="Voter model (Holley-Liggett 1975)", viz="grid_field",
   summary="Each agent copies a random neighbour's opinion.",
   watch="Watch opinion patches grow and merge until a single colour takes over (consensus).",
   effect="Opinion domains coarsen toward consensus."),
"P19": dict(name="Emergent leadership", ref="Couzin et al. 2005", viz="leadership",
   summary="A small informed minority has a preferred direction.",
   watch="Watch the few informed individuals (ringed in black, with the bold arrow as their direction) steer the whole group: the rainbow of headings collapses toward their heading despite them being a small minority.",
   effect="The uninformed majority is steered accurately by a few."),
"P20": dict(name="Quorum sensing", ref="Waters & Bassler 2005", viz="sweep_trace",
   
   summary="Agents switch ON when local signal crosses a threshold.",
   watch="Watch the collective flip ON sharply once density crosses a threshold (and lag on the way back down).",
   effect="A sharp, hysteretic collective switch at a critical density."),
"P21": dict(name="Polarization / fragmentation", ref="Hegselmann-Krause 2002", viz="histogram_time",
   args=dict(key="opinions", rng=(0.0,1.0)),
   summary="Bounded-confidence opinion dynamics.",
   watch="Watch one opinion cloud split into two or more separated camps.",
   effect="A unimodal population fragments into separated camps."),
"P22": dict(name="Information cascade / contagion", ref="SIR (Datta-Acharyya 2021)", viz="grid_field",
   args=dict(legend=["susceptible", "infected", "recovered"]),
   summary="Susceptible-infected-recovered spread on a lattice.",
   watch="Watch the infection sweep across the grid as a wavefront, leaving recovered cells behind.",
   effect="An epidemic wavefront sweeps the population."),
"P23": dict(name="Anti-coordination / load balancing", ref="Minority Game (Savit 1999)", viz="minority_game",
   args=dict(key="attendance"),
   summary="Agents win by choosing the minority side.",
   watch="Watch attendance settle into a persistent band centred on the capacity line (red dashed, half the agents) — decentralised choices self-balance the two sides round after round instead of running away.",
   effect="Attendance self-balances with sub-random (efficient) variance."),
"P24": dict(name="Homeostatic regulation", ref="Ashby 1956", viz="regulate_time",
   args=dict(key="x"),
   summary="Feedback drives a variable back to its set-point.",
   watch="Watch the state (blue) get knocked at each perturbation (gold line), then driven back close to the set-point (red dashed) by feedback — most of each disturbance is rejected, leaving only a small residual offset.",
   effect="Feedback rejects perturbations, holding the variable close to its set-point."),
"P25": dict(name="Canalized restoration / equifinality", ref="Waddington 1957", viz="pca_funnel",
   args=dict(key="state", group="trial"),
   summary="Many initial conditions flow down a canalized landscape.",
   watch="Watch many trajectories starting from very different points (blue) all funnel inward to the same final state (red) — equifinality.",
   effect="Different starts converge to the same attractor macrostate."),
"P26": dict(name="Stochastic resonance", ref="Gammaitoni 1998", viz="noise_response",
   args=dict(key="x"),
   summary="A sub-threshold signal plus tuned noise in a bistable unit.",
   watch="Note the response peaks at a middling noise level (the inverted-U) — not at zero and not at high noise.",
   effect="Optimal noise maximises signal detection (inverted-U)."),
"P27": dict(name="Spatial reciprocity", ref="Nowak & May 1992", viz="grid_field",
   args=dict(sample="even"),
   summary="Cooperators and defectors play neighbours on a lattice.",
   watch="Watch cooperators survive by huddling into clusters surrounded by defectors.",
   effect="Cooperation survives by forming spatial clusters."),
"P28": dict(name="Wealth condensation", ref="Yard-Sale (Chakraborti 2002)", viz="lorenz_time",
   args=dict(key="wealth"),
   summary="Agents repeatedly trade a random fraction of wealth.",
   watch="The Lorenz curve bowing far from the diagonal means wealth has piled up in a few hands.",
   effect="Wealth spontaneously condenses to extreme inequality."),
"P29": dict(name="Trail / network formation", ref="Tero et al. 2010 (Physarum)", viz="network_time",
   summary="Agents reinforce and evaporate trails between nodes.",
   watch="Watch redundant links fade until a lean, efficient network between the nodes remains.",
   effect="An efficient near-minimal transport network emerges."),
"P30": dict(name="Autopoiesis / boundary formation", ref="Varela-Maturana-Uribe 1974", viz="point_cloud",
   summary="Catalysis links substrate particles into a membrane that decays.",
   watch="Watch scattered link particles gather into a thin closed shell around the catalyst and hold it.",
   effect="A self-maintaining closed boundary forms and persists."),
"P31": dict(name="Delayed gratification", ref="Zhang et al. 2024", viz="bars_sort",
   args=dict(key="array"),
   summary="Agents forgo immediate reward for larger later payoff.",
   watch="Each row is one step (time runs downward); watch the colours sort into clean order.",
   effect="Per-agent restraint carries information beyond the policy label."),
"P32": dict(name="Emergent specialization", ref="Bonabeau 1996", viz="growing_spacetime",
   args=dict(key="task_assignments"),
   summary="Response-threshold agents take tasks they sense most.",
   watch="Watch agents settle onto consistent task-rows — stable specialised roles (division of labour).",
   effect="Division of labour emerges as roles differentiate."),
}
