"""Field-mediated resource competition — Pattern P37 candidate.

Ring-1 combination cell: interact = field AND conflict = competitive.

Species do not interact directly; they compete by drawing down a set of shared,
depletable resources (the 'field'). Huisman & Weissing (1999, 2001) showed that
when the resource-competition structure is cyclic (each species is the best
competitor for one resource but consumes most of another), the system never
settles: species abundances oscillate / become chaotic, and MORE species coexist
than there are limiting resources — a sustained violation of the competitive-
exclusion principle ("the paradox of the plankton").

Model (chemostat, Liebig's law of the minimum):
  mu_i(R) = r_i * min_j[ R_j / (K_ji + R_j) ]                 (growth, most-limiting resource)
  dN_i/dt = N_i ( mu_i - m_i )
  dR_j/dt = D (S_j - R_j) - sum_i C_ji mu_i N_i               (supply - consumption)

References
----------
Huisman, J. & Weissing, F.J. (1999). Biodiversity of plankton by species
    oscillations and chaos. Nature 402, 407-410.
Huisman, J. & Weissing, F.J. (2001). Biological conditions for oscillations and
    chaos generated by multispecies competition. Ecology 82, 2682-2695.
"""
from __future__ import annotations

from typing import Any, Dict, List, Tuple

import numpy as np

Built = Tuple[List[Dict[str, Any]], Dict[str, Any]]


def _integrate(N, R, K, C, S, r, m, D, t_max, dt, n_frames):
    n_steps = int(t_max / dt)
    snap = max(1, n_steps // n_frames)
    frames = [{"abundances": N.copy(), "resources": R.copy(), "step": 0}]
    for s in range(1, n_steps + 1):
        # mu_i = r_i * min_j R_j/(K_ji+R_j)
        ratio = R[:, None] / (K + R[:, None])          # (k, n)
        mu = r * ratio.min(axis=0)                     # (n,)
        dN = N * (mu - m)
        consumption = (C * (mu * N)[None, :]).sum(axis=1)   # (k,)
        dR = D * (S - R) - consumption
        N = np.clip(N + dt * dN, 0.0, None)
        R = np.clip(R + dt * dR, 0.0, None)
        if s % snap == 0:
            frames.append({"abundances": N.copy(), "resources": R.copy(), "step": s})
    return frames


def _cyclic_KC(n_species, n_resources, rng, specialist_K=0.20, generalist_K=1.0,
               consume_hi=0.10, consume_lo=0.04):
    """Cyclic resource-competition structure: species i is the best competitor for
    resource (i mod k) but consumes the most of resource ((i+1) mod k) — the
    intransitive loop that drives Huisman-Weissing oscillation."""
    K = np.full((n_resources, n_species), generalist_K)
    C = np.full((n_resources, n_species), consume_lo)
    for i in range(n_species):
        best = i % n_resources
        consume = (i + 1) % n_resources
        K[best, i] = specialist_K
        C[consume, i] = consume_hi
    # small jitter so species are not perfectly degenerate
    K *= 1.0 + 0.05 * rng.standard_normal(K.shape)
    C *= 1.0 + 0.05 * rng.standard_normal(C.shape)
    return np.clip(K, 0.02, None), np.clip(C, 0.005, None)


# Huisman & Weissing (2001) published 5-species / 5-resource parameters that
# generate sustained competitive chaos (the canonical "fundamental
# unpredictability" example). Cross-consumption is structured so no species can
# win: abundances never settle.
_HW_K = np.array([
    [0.39, 0.34, 0.30, 0.24, 0.23],
    [0.22, 0.39, 0.34, 0.30, 0.27],
    [0.27, 0.22, 0.39, 0.34, 0.30],
    [0.30, 0.24, 0.22, 0.39, 0.34],
    [0.34, 0.30, 0.22, 0.20, 0.39],
])
_HW_C = np.array([
    [0.04, 0.04, 0.07, 0.04, 0.04],
    [0.08, 0.08, 0.08, 0.10, 0.08],
    [0.10, 0.10, 0.10, 0.10, 0.14],
    [0.05, 0.03, 0.03, 0.03, 0.03],
    [0.07, 0.09, 0.07, 0.07, 0.07],
])
_HW_S = np.array([6.0, 10.0, 14.0, 4.0, 9.0])


def resource_competition(seed: int = 0, t_max: float = 3000.0, dt: float = 0.02,
                         n_frames: int = 80) -> Built:
    """Positive: Huisman-Weissing competitive chaos. 5 species compete through 5
    shared resources; abundances never reach a fixed point (sustained chaos), all
    species coexist (field-mediated, exploitative competition)."""
    rng = np.random.default_rng(seed * 7919 + 1)
    K, C = _HW_K.copy(), _HW_C.copy()
    S = _HW_S.copy()
    r = np.full(5, 1.0); m = np.full(5, 0.25)
    N0 = 0.1 + 0.02 * rng.random(5)           # seed-varied initial abundances
    R0 = S.copy()
    frames = _integrate(N0, R0, K, C, S, r, m, 0.25, t_max, dt, n_frames)
    return frames, {"model": "resource_competition", "n_species": 5,
                    "n_resources": 5, "field_mediated": True, "competitive": True}


def neg_competitive_exclusion(seed: int = 0) -> Built:
    """No cyclic structure: a clear dominance hierarchy -> competitive exclusion,
    only ~n_resources species survive at a stable equilibrium (the textbook result)."""
    rng = np.random.default_rng(seed * 104729 + 3)
    n_species, n_resources = 5, 3
    # species i better than i+1 on ALL resources -> strict hierarchy, no cycle
    K = np.zeros((n_resources, n_species))
    for i in range(n_species):
        K[:, i] = 0.15 + 0.25 * i + 0.02 * rng.standard_normal(n_resources)
    C = np.full((n_resources, n_species), 0.08) * (1 + 0.05 * rng.standard_normal((n_resources, n_species)))
    S = np.full(n_resources, 10.0); r = np.full(n_species, 1.0); m = np.full(n_species, 0.25)
    N0 = 0.1 + 0.02 * rng.random(n_species); R0 = S.copy()
    frames = _integrate(N0, R0, np.clip(K, 0.02, None), np.clip(C, 0.005, None),
                        S, r, m, 0.25, 4000.0, 0.02, 60)
    return frames, {"model": "competitive_exclusion", "n_species": n_species, "n_resources": n_resources}


def neg_stable_coexistence(seed: int = 0) -> Built:
    """5 species / 5 resources, each a clean diagonal specialist (no cross-consumption
    cycle) -> stable coexistence at a FIXED POINT. The key control: same multi-species
    coexistence as the positive, but NOT oscillating. Isolates oscillation as the signature."""
    rng = np.random.default_rng(seed * 13 + 5)
    n = 5
    # Independent niches: species i is limited ONLY by resource i (others abundant,
    # non-limiting) and consumes ONLY resource i -> 5 decoupled chemostats -> all 5
    # coexist at a stable fixed point, no oscillation.
    K = np.full((n, n), 0.02); C = np.full((n, n), 0.001)
    for i in range(n):
        K[i, i] = 0.5; C[i, i] = 0.10
    K *= 1 + 0.03 * rng.standard_normal((n, n)); C *= 1 + 0.03 * rng.standard_normal((n, n))
    S = np.full(n, 10.0); r = np.full(n, 1.0); m = np.full(n, 0.25)
    N0 = 0.1 + 0.02 * rng.random(n); R0 = S.copy()
    frames = _integrate(N0, R0, np.clip(K, 0.005, None), np.clip(C, 0.0005, None),
                        S, r, m, 0.25, 3000.0, 0.02, 80)
    return frames, {"model": "stable_coexistence", "n_species": n, "n_resources": n}


def neg_single_resource(seed: int = 0) -> Built:
    """One limiting resource, many species -> R* rule: a single winner (exclusion)."""
    rng = np.random.default_rng(seed * 31 + 7)
    n_species, n_resources = 5, 1
    K = (0.15 + 0.2 * np.arange(n_species))[None, :] * (1 + 0.03 * rng.standard_normal((1, n_species)))
    C = np.full((1, n_species), 0.08)
    S = np.full(1, 10.0); r = np.full(n_species, 1.0); m = np.full(n_species, 0.25)
    N0 = 0.1 + 0.02 * rng.random(n_species); R0 = S.copy()
    frames = _integrate(N0, R0, np.clip(K, 0.02, None), C, S, r, m, 0.25, 4000.0, 0.02, 60)
    return frames, {"model": "single_resource_exclusion", "n_species": n_species, "n_resources": n_resources}
